plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.pakredirect'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.pakredirect'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '1.1.1'
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}
